LOOT_ITEMS = [
    "wallet", "purse", "KFC Bucket", "phone", "BITCH", "AirPods", "Jordan 4s",
    "Stimulus check", "respect", "girl's number", "gold teeth", "fake chain",
    "pride", "lunch money", "catalytic converter", "rim", "Stolen Corvette Keys",
    "diamond ring", "watermelon", "fried chicken", "Kool-Aid", "Glock 17",
    "Cocaine", "Hennessy", "Tims", "Newport 100s", "whole rack", "Percocet",
    "Double Cup", "Ski Mask", "9mm", "Jordan 11s", "Dior Puffy Jacket",
    "Amiri Jeans", "B.B. Simon Belt", "Vlone Shirt", "Cartier Glasses",
    "Stolen EBT Card", "Trap Phone", "Bag of Zaza", "Promethazine Bottle",
    "Gold Grillz", "Designer Ski Mask", "Stolen Hellcat Keys", "Stack of Blue Hundreds",
    "Diamond Link Chain", "Supreme Money Gun", "Chrome Heart Ring", "Off-White Belt",
    "Yeezy Slides", "iPhone 15", "Brick of White", "Glock Drum Mag", "Moncler Vest",
    "Balenciaga Track Runners", "Stolen Link Card", "Cup of Wock", "Foreign Whip",
    "Stolen Airfryer", "Box of Backwoods", "Faygo Bottle", "Section 8 Voucher",
    "Court Date Paperwork", "Child Support Notice", "Warrant for Arrest",
    "Bag of Flaming Hot Cheetos", "Half-eaten Turkey Leg", "Stolen Porch Package",
    "Gently Used Pitbull", "Respect", "Huzz", "BITCHES", "Broken PlayStation 4",
    "Bottle of Blue Nuvo", "Fake Gucci Wallet", "Gas Station Sushi",
    "Used Scratch-off Ticket", "backpack", "duffel bag", "snapback", "beanie",
    "hoodie", "AA cup bra", "A cup bra", "B cup bra", "C cup bra", "D cup bra",
    "DD cup bra", "DDD cup bra", "E cup bra", "F cup bra", "G cup bra", "H cup bra",
    "I cup bra", "J cup bra", "K cup bra", "L cup bra", "M cup bra", "N cup bra",
    "O cup bra", "P cup bra", "Q cup bra", "sweatpants", "joggers", "jordan 4s",
    "air force 1", "nike air max", "adidas superstars", "fila disruptor",
    "vans sk8-hi", "converse chucks", "timberland boots", "slides", "crocs",
    "grillz", "cuban link chain", "rope chain", "watch", "casio watch", "g-shock",
    "bracelet", "earrings", "rings", "necklace", "pendant", "headphones",
    "earbuds", "portable speaker", "bluetooth speaker", "laptop", "tablet",
    "charger", "usb cable", "airpods", "ps5", "xbox", "switch", "video games",
    "skateboard", "bmx bike", "basketball", "soccer ball", "baseball glove",
    "box gloves", "energy drink", "monster", "red bull", "rockstar", "kool-aid",
    "sprite", "coca-cola", "pepsi", "mountain dew", "2-liter soda", "candy",
    "chips", "takis", "hot cheetos", "gum", "ice cream", "cookie", "snack cakes",
    "hennessy", "crown royal", "smirnoff", "vodka", "rum", "beer", "cheap wine",
    "blunt wrap", "rolling papers", "grinder", "bong", "pipe", "vape pen",
    "vape juice", "hookah", "ashtray", "zip bags", "rubber bands", "safe",
    "cheap safe", "mini fridge", "lamp", "led lights", "lava lamp", "wall poster",
    "rapper poster", "car poster", "vinyl record", "cd", "dvd", "blu-ray",
    "board game", "playing cards", "dice", "sticker", "graffiti marker",
    "spray paint", "stencil", "wallet chain", "belt chain", "phone chain",
    "fanny pack", "tote bag", "backpack chain", "cheap rims", "hubcaps",
    "spoiler", "steering wheel cover", "seat cover", "floor mats", "dashboard cover",
    "car air freshener", "windshield decal", "rear window sticker", "hood decal",
    "neon underglow", "car subwoofer", "amplifier", "jumper cables", "tire inflator",
    "oil funnel", "car jack", "tool kit", "screwdriver set", "wrench set",
    "socket set", "cheap perfume", "cologne", "hat", "bucket hat", "visor",
    "scarf", "gloves", "fingerless gloves", "arm sleeves", "wristband",
    "headband", "shoe lace", "charms", "cheap belt", "designer knockoff belt",
    "cheap hoodie", "cheap pants", "cheap tee", "graphic tee", "sports jersey",
    "track jacket", "windbreaker", "denim jacket", "puffer jacket", "flannel",
    "camouflage pants", "leggings", "shorts", "tank top", "crop top", "slides",
    "slippers", "flip-flops", "house slippers", "socks", "thermal underwear",
    "long johns", "anklet", "toe ring", "cheap grill", "fake diamond ring",
    "fake chain", "fake watch", "phone case", "custom phone case", "laptop sticker",
    "car sticker", "fast food bag", "mcdonalds fries", "wendys spicy nuggets",
    "popeyes chicken", "taco bell taco", "jack in the box tacos", "burger king whopper",
    "pizza slice", "hot pockets", "frozen burrito", "ramen noodles", "cup noodles",
    "cheetos", "takis", "doritos", "king size candy bar", "soda can", "slushie",
    "icees", "kool-aid pouch", "fruit punch", "energy drink can", "hennessy mini",
    "crown royal mini",
]

# New: Collectibles
COLLECTIBLES = {
    "golden_chain": {"name": "Golden Chain", "rarity": "legendary", "value": 5000, "description": "A shiny chain that screams boss status."},
    "rare_sneakers": {"name": "Rare Jordans", "rarity": "epic", "value": 3000, "description": "Limited edition kicks that turn heads."},
    "diamond_grill": {"name": "Diamond Grill", "rarity": "rare", "value": 1500, "description": "Blings your teeth like a superstar."},
    "vintage_watch": {"name": "Vintage Rolex", "rarity": "legendary", "value": 10000, "description": "Timepiece from the old heads."},
    "street_art": {"name": "Street Art Piece", "rarity": "epic", "value": 2500, "description": "Graffiti masterpiece worth displaying."},
    "hood_trophy": {"name": "Hood Trophy", "rarity": "rare", "value": 1000, "description": "Proof of your street victories."},
}

# New: Investment Businesses
BUSINESSES = {
    "trap_house": {"name": "Trap House", "base_yield": 100, "upgrade_cost": 5000, "description": "Passive income from the block."},
    "corner_store": {"name": "Corner Store", "base_yield": 150, "upgrade_cost": 7500, "description": "Sell snacks and essentials."},
    "car_wash": {"name": "Car Wash", "base_yield": 200, "upgrade_cost": 10000, "description": "Clean whips for the hood."},
    "barbershop": {"name": "Barbershop", "base_yield": 250, "upgrade_cost": 12500, "description": "Fade heads and build rep."},
}

# New: Black Market Items
BLACK_MARKET_ITEMS = [
    "stolen_tv", "fake_id", "hot_phone", "counterfeit_money", "illegal_fireworks", "bootleg_dvd"
]

QUOTES = [
    "Black lives matter", "Fly High King Von", "Do you got fried chicken?",
    "Pass me the joint", "i joined the crips", "OH SHIT THE ONE TIME",
    "FREE MY NIGGA MELLY", "I'm really out here hooping", "Hold this 9mm for me",
    "Father? Never heard of him", "Bout to abandon some kids real quick",
    "Pants sagged so low you can see the future", "Niggas really be tripping",
    "On god for real", "I'm really the king of the hood", "Stop looking at my bitch",
    "Yo can I borrow $5? I'll pay you back on Tuesday", "12 is on the way, hide the strap!",
    "Who want some koolaid?", "I'm just tryna hoop and stay out the way",
    "Slide for Von", "Big GDK", "I'm smoking on that pack", "Got the glizzy on me",
    "On folks grave", "Spinning the block", "Free the guys", "Free the real",
    "Street code over everything", "Don't be a snitch, nobody likes a rat",
    "Hustle hard or stay broke", "From the mud to the top",
    "Keep your circle small and your glock loaded", "Trust nobody, not even your own shadow",
    "Moving in silence like lasagna", "Respect is earned, not given",
    "Trap house jumping today", "Money talks, bullshit walks",
    "Every day is a struggle in the trenches", "Keep it 100 or keep it away from me",
    "Loyalty is royalty", "Stay dangerous, the ops are watching",
    "Finessing the system daily", "Concrete jungle dreams", "Living fast, dying young",
    "The block is hot, stay low", "Real recognizes real", "Doing it for the set",
    "I'm really out here spinning for the guys", "Smoking on that dead opp pack",
    "We outside till the sun come up", "Ain't no love in these streets",
    "Glizzy in the Dior bag, don't trip", "I'm really a trench baby",
    "Stop claiming my set, you a civilian", "Bout to go for a drill real quick",
    "Free Young Thug till it's backwards", "I'm popping percs till I can't feel my face",
    "Moving weight like a bodybuilder", "Don't get smoked like a backwood",
    "I really came from nothing", "The plug just called, gotta run",
    "Sipping lean out a styrofoam cup", "My glock got a switch, don't make me use it",
    "On my momma I'm really like that", "No face, no case",
    "Keep that same energy when I see you", "I'm just tryna see my brothers win",
    "Hood legend in the making", "Trap phone ringing off the hook",
    "I'm really a street pharmacist", "They talk behind my back cause they can't front",
    "Gotta stay focused on the bag", "The streets ain't for the weak",
    "I'm really a product of my environment", "Big pressure, no diamonds",
    "I'm really a hood superstar", "Don't get it twisted, I'm really outside",
    "I'm really built for this shit", "They hating on the glow up",
    "Moving smart, staying sharp", "I'm really a trench king",
    "The marathon continues, long live Nip", "Stay true to yourself, fuck the rest",
    "I'm really a diamond in the rough", "They tried to bury me, they didn't know I was a seed",
    "I'm really a street poet", "The grind never stops", "You see the laser? Don't move.",
    "My baby mama trippin again", "Just beat the case, let's celebrate",
    "I'm smoking zaza in the library", "Why you lookin at my chain like that?",
    "I really got it out the mud", "Told the judge I was hooping",
    "My lawyer is Jewish, I'm straight", "Moving silent like the 'g' in gnome",
    "I'm the one who knocks... at the trap house", "The feds took my pictures, I'm famous",
    "Just finessed a scammer, recursion!", "Pockets fat like Biggie",
    "I'm really a certified stealer", "Don't make me get the guys involved",
    "I'm spinning the block in a Prius", "Save some chicken for me",
    "I'm really a spiritual driller", "My glock got personality",
    "I'm popping out at the cookout", "Stop asking for a discount, the price is the price",
    "I'm really him, no cap",
]

STEAL_ITEMS = LOOT_ITEMS

KILL_MESSAGES = [
    "died from their own stupidity.",
    "stubbed their toe and died.",
    "choked on air.",
    "tried to drink bleach but missed.",
    "got hit by a falling piano.",
    "was scared to death by their own reflection.",
    "forgot how to breathe.",
    "tried to fight a goose and lost.",
    "ate too many hot wings and ascended.",
    "slipped on a banana peel and hit their head.",
    "was killed by a rogue shopping cart.",
    "fell into a manhole while texting.",
    "got lost in a corn maze and gave up.",
    "was flattened by a vending machine.",
    "tried to pet a lion.",
    "died of cringe.",
    "was eliminated by a Minecraft bed.",
    "forgot to save and got overwritten.",
    "was deleted by a system update.",
    "drowned in a puddle.",
    "was crushed by a stack of pancakes.",
    "had a heart attack from bad grammar.",
    "was vaporized by a laser pointer.",
    "got abducted by aliens and probed to death.",
    "was smited by an angry god.",
    "died of laughter from a terrible joke.",
    "was beaten to death by a angry mob of gnomes.",
    "fell off a cliff while taking a selfie.",
    "was buried alive by their own ego.",
    "exploded for no reason.",
    "was disintegrated by a microwave.",
    "tried to time travel and got stuck in a wall.",
    "was erased from existence by a paradox.",
    "died of boredom during this command.",
    "was killed by a wild Karen.",
    "got doxxed and died of shame.",
    "was roasted so hard they combusted.",
    "drank expired milk and perished.",
    "was taken out by a boomerang.",
    "fell into a black hole.",
    "was smacked by a flying fish.",
    "got hit by a stray bullet from a Nerf war.",
    "was poked by a very sharp stick.",
    "died of FOMO.",
    "was scared by a shadow.",
    "fell asleep and never woke up.",
    "was unplugged mid-sentence.",
    "got folded like laundry.",
    "was yeeted into the sun.",
    "lost a staring contest with the sun.",
    "was killed by a hypothetical question.",
    "died waiting for the bus.",
    "was done in by a rogue sock.",
    "choked on a watermelon seed.",
    "was assassinated by a ninja squirrel.",
    "got taken out by a rogue Roomba.",
    "was defeated by a level 1 slime.",
    "fell into a pit of marshmallows and suffocated.",
    "was beaten by a grandma with a purse.",
    "died from a paper cut that got infected.",
    "was struck by lightning while holding a metal stick.",
    "got hit by a car while crossing the street legally.",
    "was killed by a falling coconut.",
    "drank too much lean and flatlined.",
    "was smoked by the opps.",
    "got caught lacking and never recovered.",
    "was finished by a critical hit.",
    "died of secondhand embarrassment.",
]

# ===== SHOP ITEMS =====
SHOP_ITEMS = {
    "magnet": {"cost": 1000, "type": "multiplier", "mult": 1.5, "name": "Bread Magnet"},
    "oven": {"cost": 5000, "type": "multiplier", "mult": 2.0, "name": "Industrial Oven"},
    "kneader": {"cost": 15000, "type": "multiplier", "mult": 3.0, "name": "Gold Kneader"},
    "safe_box": {"cost": 2500, "type": "capacity", "amount": 500, "name": "Safe Box"},
    "safe_upgrade": {"cost": 5000, "type": "capacity", "amount": 5000, "name": "Safe Upgrade"},
    "lucky_charm": {"cost": 10000, "type": "consumable", "name": "Lucky Charm"},
    "jail_card": {"cost": 7500, "type": "consumable", "name": "Bail Bond"},
    "energy_drink": {"cost": 5000, "type": "consumable", "name": "Energy Drink"},
    "mask": {"cost": 15000, "type": "equipment", "name": "Ski Mask"},
    "weapon": {"cost": 25000, "type": "equipment", "name": "Strap"},
    "car": {"cost": 50000, "type": "equipment", "name": "Whip"},
    "chain": {"cost": 5000, "type": "drip", "value": 10, "name": "Gold Chain"},
    "grillz": {"cost": 8000, "type": "drip", "value": 15, "name": "Gold Grillz"},
    "watch": {"cost": 15000, "type": "drip", "value": 20, "name": "Rolex"},
    "weed_seed": {"cost": 100, "type": "drug_seed", "name": "Weed Seed"},
    "coke_brick": {"cost": 5000, "type": "drug", "name": "Cocaine Brick"},
    "pills": {"cost": 2000, "type": "drug", "name": "Pills"},
    "pass": {"cost": 50000, "type": "special", "name": "Monthly Pass"},
    "bulletproof_vest": {"cost": 30000, "type": "equipment", "name": "Bulletproof Vest"},
    "burner_phone": {"cost": 2500, "type": "equipment", "name": "Burner Phone"},
    "fake_id": {"cost": 10000, "type": "consumable", "name": "Fake ID"},
    "lockpick_set": {"cost": 8000, "type": "equipment", "name": "Lockpick Set"},
    "crowbar": {"cost": 12000, "type": "equipment", "name": "Crowbar"},
    # Prestige items requiring street cred
    "respect_boost": {"cost": 25000, "street_cred_req": 50, "type": "prestige", "name": "Respect Boost", "description": "Permanently increases your respect by 25"},
    "cred_multiplier": {"cost": 50000, "street_cred_req": 100, "type": "prestige", "mult": 1.25, "name": "Street Cred Multiplier", "description": "1.25x multiplier for all earnings"},
    "hood_pass": {"cost": 75000, "street_cred_req": 150, "type": "prestige", "name": "VIP Hood Pass", "description": "Access to exclusive hood events and 10% better payouts"},
    "legendary_chain": {"cost": 100000, "street_cred_req": 200, "type": "prestige", "drip": 50, "name": "Legendary Chain", "description": "Ultimate drip piece (+50 drip level)"},
}

SHIKYO_SERVICES = {
    "custom_color": {"cost": 50000, "name": "Custom Color Role", "description": "Get a role with a color of your choice!"},
    "hard_r_pass": {"cost": 100000, "name": "Hard R Pass", "description": "Immunity from N-word heat."},
}