ROAST_CATEGORIES = {
    "appearance": [
        "You look like what happens when you press 'randomize' on a character creator.",
        "I've seen better-looking potatoes.",
        "If ugliness was a crime, you'd get life without parole.",
        "You look like a before picture.",
        "Your face makes onions cry.",
        "You look like a mistake, but someone made you twice.",
        "When you were born, the doctor slapped your parents.",
        "You're so ugly, when you look in the mirror, your reflection looks away.",
        "You have the kind of face that makes people appreciate their own.",
        "Your birth certificate is an apology letter from the condom factory.",
        "You look like a Picasso painting that fell down the stairs.",
        "Your face could scare a hungry bear away from a picnic.",
        "You look like you were drawn by someone who's never seen a human.",
        "If your face was a movie, it would be directed by M. Night Shamalan and still suck.",
        "You look like a Walmart brand version of a person.",
        "Your reflection probably asks for a different mirror.",
        "You're so ugly,; you make blind kids cry.",
        "Your face looks like it caught on fire and someone put it out with a fork.",
        "You look like a mistake, but in 4K.",
        "If you were a spice, you'd be flour.",
    ],
    "intelligence": [
        "You have two brain cells and they're both fighting for third place.",
        "If brains were dynamite, you wouldn't have enough to blow your nose.",
        "You're about as sharp as a marble.",
        "I'd explain it to you, but I don't have any crayons with me.",
        "You're the reason they put instructions on shampoo bottles.",
        "Your idea of a balanced diet is a chip in each hand.",
        "You couldn't pour water out of a boot if the instructions were on the heel.",
        "You're not the stupidest person on the planet, but you better hope they don't die.",
        "You have the IQ of a grilled cheese sandwich.",
        "You're like a cloud—when you disappear, it's a beautiful day.",
        "You're dumber than a box of rocks, and the rocks are smarter.",
        "If stupidity was a sport, you'd be the MVP.",
        "You're the human equivalent of a 404 error.",
        "You're about as useful as a screen door on a submarine.",
        "You have the mental capacity of a goldfish with amnesia.",
        "You're proof that evolution can go in reverse.",
        "You're so dumb you think Taco Bell is a Mexican phone company.",
        "You'd struggle to pour water out of a boot with instructions on the heel.",
        "You're not stupid; you just have bad luck thinking.",
        "You have the problem-solving skills of a broken calculator.",
    ],
    "personality": [
        "Your personality is like a haunted house—scary and empty.",
        "If personality were money, you'd be broke.",
        "You're the human equivalent of a participation trophy.",
        "You're about as useful as a chocolate teapot.",
        "You bring everyone so much joy... when you leave the room.",
        "You're like a software update—every time I see you, I think 'not now'.",
        "You're the reason the gene pool needs a lifeguard.",
        "You have the charm of a wet paper bag.",
        "You're not annoying, you're just... naturally unlikable.",
        "You're the human version of a typo.",
        "You have the personality of a dial-up modem.",
        "You're as interesting as watching paint dry, but less colorful.",
        "You have the charisma of a damp rag.",
        "Your personality is so bland, you make mayonnaise look spicy.",
        "You're the human equivalent of beige wallpaper.",
        "You're as exciting as a tax form.",
        "You have the social skills of a cactus.",
        "You're like a human snooze button.",
        "Your presence is as welcome as a fart in a spacesuit.",
        "You're the reason some animals eat their young.",
    ],
    "hood": [
        "You tryna be hard but your gang sign looks like you're ordering a pizza.",
        "You claim the streets but you get nervous when the ice cream truck plays music.",
        "You talk about trapping but your biggest sale was lemonade in 2012.",
        "You say you're from the trenches but you flinch when a plastic bag blows by.",
        "You got 'street cred' from watching Power.",
        "You claim you're a shooter but the only thing you're popping is bubble wrap.",
        "You talk about your 'ops' but your biggest enemy is your WiFi password.",
        "You say you're outside but you're really in your mom's basement.",
        "You claim you're a kingpin but your plug is Amazon Prime.",
        "You talk about drippin' but your chain came from a vending machine.",
        "You claim you're a driller but you still ask your mom for permission to stay out late.",
        "You say you're 'really from the hood' but your address has an HOA.",
        "You talk about spinning blocks but you get lost in a parking lot.",
        "You claim you're a street pharmacist but you're selling Flintstones vitamins.",
        "You say you're about that life but you're scared of fireworks.",
        "You talk about your 'strap' but you're holding a water gun.",
        "You claim you're a OG but you were born in 2005.",
        "You say you're a trap star but you're still using an allowance.",
        "You talk about your 'gang' but it's just you and your cat.",
        "You claim you're a king but your crown came from Burger King.",
        "You talk about your 'crew' but it's just you and your Xbox Live friends.",
        "You claim you're a trapper but your biggest hustle is selling Girl Scout cookies.",
        "You say you're 'street smart' but you still fall for Nigerian prince emails.",
        "You talk about your 'territory' but it's just your backyard.",
    ],
    "savage": [
        "Your existence is an argument for birth control.",
        "You're the reason they invented the middle finger.",
        "I'd agree with you but then we'd both be wrong.",
        "You're not stupid; you just have bad luck thinking.",
        "I don't know what makes you so stupid, but it really works.",
        "You're like a penny—two-faced and worthless.",
        "If laughter is the best medicine, your face must be curing the world.",
        "You're proof that evolution can go in reverse.",
        "I'd roast you but my mom said not to burn trash.",
        "You're the reason aliens won't talk to us.",
        "You're about as useful as a fork in a soup kitchen.",
        "You're the human equivalent of a participation trophy.",
        "You have the face of a person who'd return a Christmas gift to an orphan.",
        "You're so dense, light bends around you.",
        "You're the reason they put warning labels on everything.",
        "You have the warmth of a dead star.",
        "You're like a broken pencil—pointless.",
        "You're the reason some people believe in sterilization.",
        "You're about as helpful as a parachute that opens on the second bounce.",
        "You're the human version of a 'do not resuscitate' order.",
    ],
}

RANDOM_ROASTS = [roast for cat in ROAST_CATEGORIES.values() for roast in cat]

HARD_R_REPLIES = [
    "AYO WHO TF YOU THINK YOU IS SAYING THAT WITH THE HARD R? YOU AIN'T EVEN FROM THE BLOCK, YOU PROBABLY FROM SUBURBIA WITH YOUR WHITE ASS.",
    "OH NAH, I KNOW YOU DIDN'T JUST DROP THE HARD R. I SEEN YOUR PROFILE PIC, YOU LOOK LIKE YOU DRINK SOY MILK AND DO YOGA.",
    "YOU REALLY OUT HERE SAYING 'NIGGER' WHEN YOUR GRANDPA PROBABLY OWNED MY GREAT GRANDPA. THE AUDACITY IS CRAZY.",
    "BOY IF YOU DON'T GET YOUR WANNABE ASS OUTTA HERE. YOU PROBABLY LISTEN TO IGGY AZALEA AND THINK YOU'RE DOWN.",
    "HARD R? HARD R? YOU LOOK LIKE YOU GET SUNBURNED WATCHING THE NEWS. SIT YOUR VANILLA ASS DOWN.",
    "WHO LET YOU COOK? YOU SAYING 'NIGGER' LIKE YOU EVER BEEN ANYWHERE NEAR THE TRENCHES. YOU PROBABLY THINK 'THE WIRE' IS A DOCUMENTARY.",
    "YOU DROPPING N-BOMBS BUT YOUR LAST MEAL WAS AVOCADO TOAST. BE FOR REAL.",
    "YOU SAYING N-WORDS ALL LOUD? YO ASS IS THE REASON ISRAEL BOMBED PALESTINE, NIGGUH!",
    "I CAN TELL BY HOW YOU TYPE YOU WHITE. YOU USING PROPER PUNCTUATION AND SHIT. NIGGAS DON'T USE SEMICOLONS.",
    "YOU SAID THE HARD R WITH YOUR CHEST BUT I BET YOU CROSS THE STREET WHEN YOU SEE A GROUP OF BLACK PEOPLE.",
    "MY NIGGA YOU AIN'T BLACK, YOU WHITER THAN MAYONNAISE IN A SNOWSTORM. STOP PLAYING.",
    "YOU GOT THE AUDACITY TO SAY 'NIGGER' BUT YOUR FAMILY TREE STRAIGHTER THAN THE LINE AT THE DMV.",
    "NAH, YOU REALLY JUST SAID THAT? I BET YOUR ANESTORS ARE ROLLING IN THEIR GRAVES FROM EMBARRASSMENT.",
    "YOU'RE WHITER THAN A GHOST IN A CLOUD OF FLOUR. SIT DOWN BEFORE I CALL YOUR MAMA.",
    "I KNOW YOU DIDN'T JUST TYPE 'NIGGER' FROM YOUR PARENTS' BASEMENT. GET A JOB.",
    "THE ONLY THING YOU KNOW ABOUT THE STREETS IS HOW TO GET TO WHOLE FOODS. CHILL.",
    "YOU PROBABLY CAN'T EVEN SEASON CHICKEN RIGHT. DON'T TALK TO ME ABOUT NOTHING.",
    "YOU'RE OUT HERE SAYING THE HARD R BUT YOU PROBABLY STILL ASK YOUR MOM FOR PERMISSION TO STAY UP PAST 10.",
    "NAH THIS CAN'T BE REAL. YOU TYPE LIKE YOU WEAR SOCKS WITH SANDALS. EMBARRASSING.",
    "YOU'RE THE REASON YOUR ANCESTORS LOST THE CIVIL WAR. WEAK GENES.",
    "I BET YOU THINK 'CRACKER' IS A RACIAL SLUR TOO. SNOWFLAKE ASS.",
    "YOU DROPPING THE HARD R LIKE YOU EVER HAD TO DEAL WITH REDLINING. YOUR BIGGEST HOUSING ISSUE IS CHOOSING BETWEEN GRANITE OR QUARTZ COUNTERTOPS.",
    "HARD R COMING FROM SOMEONE WHO PROBABLY CALLS THE COPS WHEN THEY HEAR LOUD MUSIC. YOU'RE THE NEIGHBORHOOD SNITCH BY DEFAULT.",
    "YOU SAID 'NIGGER' BUT YOUR SOUL IS AS COLORLESS AS YOUR DIET OF UNSEASONED CHICKEN. BASIC ASS.",
    "THE AUDACITY TO USE THE HARD R WHEN YOU CAN'T EVEN CLAP ON BEAT. YOUR RHYTHM IS AS OFF AS YOUR MORALS.",
    "WHO LET YOU OUT THE SUBURBS? DROPPING N-BOMBS BUT YOU GET SCARED WHEN A FIREWORK GOES OFF. PUSSY ASS.",
    "YOU USING THE HARD R LIKE YOU EVER FACED DISCRIMINATION. YOUR ONLY DISCRIMINATION IS WHETHER TO GET REGULAR OR DECAF.",
    "HARD R WITH YOUR PRIVILEGED ASS? YOU PROBABLY THINK SYSTEMIC RACISM IS A MYTH. EDUCATE YOURSELF.",
    "YOU SAID 'NIGGER' BUT YOU CAN'T EVEN HANDLE MILD SAUCE. YOUR PALATE IS AS WEAK AS YOUR CHARACTER.",
    "THE ONLY THING HARD ABOUT YOU IS YOUR HEAD FROM BEING SO DENSE. YOU'RE THE HUMAN VERSION OF A PARTICIPATION TROPHY.",
    "YOU DROPPING THE HARD R LIKE YOU EVER HAD TO CODE-SWITCH. YOUR ONLY SWITCH IS FROM BUSINESS CASUAL TO CASUAL FRIDAY.",
    "HARD R COMING FROM SOMEONE WHOSE CULTURE IS STARBUCKS AND APPLEBEES. YOU AIN'T GOT NO SAUCE.",
    "YOU OUT HERE USING SLAVE OWNER LANGUAGE BUT YOU GET ANXIETY IN A CROWD. PICK A STRUGGLE.",
    "YOU SAID 'NIGGER' WITH YOUR WHOLE CHEST BUT YOUR BLOODLINE IS AS PLAIN AS WONDER BREAD. BORING ASS.",
    "THE HARD R FROM SOMEONE WHO PROBABLY THINKS 'WAKANDA' IS A REAL PLACE. YOU'RE EMBARRASSING.",
    "YOU USING THAT WORD LIKE YOU EVER HAD TO WORRY ABOUT DRIVING WHILE BLACK. YOUR ONLY WORRY IS MERGING ON THE HIGHWAY.",
    "HARD R BUT YOU CAN'T EVEN COOK A POT OF RICE RIGHT. YOUR SEASONING CONSISTS OF SALT AND REGRET.",
    "YOU DROPPING N-BOMBS BUT YOUR MUSIC TASTE IS COLDPLAY AND MUMFORD & SONS. YOU AIN'T STREET, YOU SUBURBAN.",
    "YOU SAID 'NIGGER' LIKE YOU EVER BEEN ANYWHERE NEAR A PROJECT. YOUR IDEA OF THE HOOD IS WHEN YOUR UBER TAKES A WRONG TURN.",
    "THE AUDACITY TO USE THE HARD R WHEN YOU PROBABLY CAN'T NAME 5 BLACK HISTORICAL FIGURES. IGNORANT ASS.",
    "HARD R COMING FROM SOMEONE WHOSE BIGGEST TRAUMA IS THEIR PHONE BATTERY DYING. PRIVILEGE IS SHOWING.",
    "YOU USING THAT WORD BUT YOU STILL LIVE WITH YOUR PARENTS AT 30. FOCUS ON GETTING YOUR OWN PLACE FIRST.",
    "YOU DROPPING THE HARD R LIKE YOU EVER HAD TO WORK TWICE AS HARD FOR HALF THE RECOGNITION. YOUR DADDY GOT YOU THAT JOB.",
    "HARD R FROM SOMEONE WHO PROBABLY THINKS 'BLACK LIVES MATTER' IS A TREND. YOU'RE PART OF THE PROBLEM.",
    "YOU SAID 'NIGGER' BUT YOUR FAMILY REUNIONS ARE QUIETER THAN A LIBRARY. NO RHYTHM, NO CULTURE, NOTHING.",
    "THE HARD R COMING FROM A KEYBOARD WARRIOR WHO WOULDN'T SAY THAT SHIT IN PERSON. INTERNET GANGSTER.",
    "YOU USING THAT WORD LIKE YOU EVER HAD TO DEAL WITH MICROAGGRESSIONS. YOUR ONLY AGGRESSION IS WHEN THE BARISTA GETS YOUR ORDER WRONG.",
    "HARD R BUT YOU CAN'T EVEN GROW FACIAL HAIR. YOU LOOK LIKE A PREPUBESCENT BOY TRYING TO BE EDGY.",
    "YOU DROPPING N-BOMBS BUT YOUR IDEA OF DANGER IS A 'CHECK ENGINE' LIGHT. YOU AIN'T SEEN NO REAL PROBLEMS.",
    "YOU SAID 'NIGGER' WITH CONFIDENCE BUT YOU STILL ASK FOR PERMISSION TO USE THE BATHROOM. GROW UP.",
    "THE AUDACITY TO USE THE HARD R WHEN YOU PROBABLY CAN'T EVEN NAME 3 BLACK AUTHORS. YOUR EDUCATION FAILED YOU.",
    "HARD R COMING FROM SOMEONE WHOSE ENTIRE PERSONALITY IS CRAFT BEER AND CROSSFIT. YOU BASIC AS HELL.",
    "YOU USING THAT WORD BUT YOU GET NERVOUS WHEN CASHIERS MAKE EYE CONTACT. SOCIAL ANXIETY AND RACISM IS A WILD COMBO.",
    "YOU DROPPING THE HARD R LIKE YOU EVER HAD TO WORRY ABOUT YOUR HAIR BEING 'PROFESSIONAL'. YOUR HAIRCUT IS FROM GREAT CLIPS.",
    "HARD R FROM SOMEONE WHO PROBABLY THINKS SOUL FOOD IS JUST 'FRIED CHICKEN'. YOUR CULTURAL IGNORANCE IS SHOWING.",
    "YOU SAID 'NIGGER' BUT YOU CAN'T EVEN DOUBLE DUTCH. YOU LACK COORDINATION AND COMMON SENSE.",
    "THE HARD R COMING FROM A PERSON WHO STILL USES INTERNET EXPLORER. YOU'RE OUTDATED IN EVERY WAY.",
    "YOU USING THAT WORD LIKE YOU EVER HAD TO REPRESENT YOUR ENTIRE RACE. YOUR ONLY REPRESENTATION IS YOUR FANDOM FOR THE OFFICE.",
    "HARD R BUT YOU PROBABLY THINK JIM CROW WAS A PERSON. HISTORICALLY ILLITERATE ASS.",
    "YOU DROPPING N-BOMBS BUT YOUR BIGGEST ACCOMPLISHMENT IS FINISHING A NETFLIX SERIES. AIM HIGHER.",
    "YOU SAID 'NIGGER' WITH YOUR WHOLE CHEST BUT YOU STILL WEAR LIGHT UP SNEAKERS. YOU AIN'T GROWN, YOU GROWING OLD.",
    "THE AUDACITY TO USE THE HARD R WHEN YOU CAN'T EVEN MAKE INSTANT RAMEN RIGHT. YOU'RE USELESS.",
    "HARD R COMING FROM SOMEONE WHOSE IDEA OF ADVENTURE IS TRYING A NEW CHAIN RESTAURANT. YOU'RE NOT DANGEROUS, YOU'RE BORING.",
    "YOU USING THAT WORD BUT YOU PROBABLY THINK 'CODE SWITCHING' IS SOMETHING PROGRAMMERS DO. CLUELESS ASS.",
    "YOU DROPPING THE HARD R LIKE YOU EVER HAD TO TEACH YOUR KIDS HOW TO INTERACT WITH POLICE. YOUR KIDS' BIGGEST FEAR IS BEDTIME.",
    "HARD R FROM SOMEONE WHO PROBABLY THINKS AFFIRMATIVE ACTION IS REVERSE RACISM. CHECK YOUR PRIVILEGE, THEN CHECK YOURSELF.",
    "YOU SAID 'NIGGER' BUT YOU CAN'T EVEN NAME THREE BLACK NEIGHBORHOODS IN YOUR CITY. YOU LIVE IN A BUBBLE.",
    "THE HARD R COMING FROM A PERSON WHO STILL GETS AN ALLOWANCE. GET YOUR OWN MONEY BEFORE YOU GET YOUR OWN OPINIONS.",
    "YOU USING THAT WORD LIKE YOU EVER HAD TO WORRY ABOUT SUNGLASSES BEING TOO DARK. YOUR SKIN IS TRANSLUCENT.",
    "HARD R BUT YOUR CULTURAL REFERENCES ARE FROM TIKTOK WHITE BOYS. YOU HAVE NO ORIGINALITY.",
    "YOU DROPPING N-BOMBS BUT YOU GET LOST USING PUBLIC TRANSPORTATION. YOU AIN'T STREET SMART, YOU STREET DUMB.",
    "YOU SAID 'NIGGER' WITH CONFIDENCE BUT YOU STILL USE TRAINING WHEELS ON YOUR BIKE. LITERAL CHILD BEHAVIOR.",
]

SOFT_A_REPLIES = [
    "AYO WHO TF GAVE YOU THE PASS? YOU AIN'T MY NIGGA, YOU A CUSTOMER AT STARBUCKS.",
    "OH YOU THINK YOU CAN SAY 'NIGGA' CUZ YOU LISTEN TO DRILL MUSIC? YOU PROBABLY FROM CONNECTICUT.",
    "YOU'RE WHITER THAN A SHEET OF PAPER IN A BLIZZARD. DON'T EVER CALL ME YOUR NIGGA.",
    "I KNOW YOU DIDN'T JUST SAY 'NIGGA' WITH YOUR EUROPEAN ASS. YOUR FAMILY PROBABLY STILL HAS A CASTLE.",
    "YOU CAN'T SAY THAT WORD. YOU LOOK LIKE YOU'VE NEVER SEEN A FIGHT IN YOUR LIFE.",
    "MY NIGGA? MY NIGGA? YOU AIN'T MY NIGGA, YOU A WHITE BOY FROM THE SUBURBS.",
    "YOU PROBABLY THINK CHICKEN AND WAFFLES IS EXOTIC. SIT DOWN.",
    "I CAN SMELL THE PRIVILEGE THROUGH THE SCREEN. STOP IT.",
    "YOU'RE THE TYPE TO SAY 'NIGGA' ONLINE BUT CLUTCH YOUR PURSE IN REAL LIFE.",
    "YOU CAN'T EVEN DANCE AND YOU TRYNA SAY 'NIGGA'? THE AUDACITY.",
    "YOUR ENTIRE PERSONALITY IS BASED ON RAP MUSIC YOU DON'T UNDERSTAND. SAD.",
    "YOU PROBABLY THINK 'NO CAP' MEANS YOU'RE NOT WEARING A HAT. I'M DONE.",
    "YOU'RE OUT HERE USING AAVE BUT YOUR REAL VOICE SOUNDS LIKE A NPR HOST.",
    "I BET YOU PRONOUNCE IT 'NI-GUH' LIKE YOU'RE ORDERING AT A FRENCH RESTAURANT.",
    "YOU'RE WHITER THAN THE INSIDE OF A BANANA. STOP TRYING TO BE DOWN.",
    "THE ONLY GANG YOU'RE IN IS THE BOOK CLUB. CHILL.",
    "YOU PROBABLY THINK 'OPPS' MEANS OPPORTUNITIES. I CAN'T.",
    "YOUR IDEA OF BEING 'STREET' IS USING THE EXPRESS LANE AT TARGET. BYE.",
    "YOU CAN'T SAY 'NIGGA' WHEN YOUR BIGGEST PROBLEM IS YOUR MACBOOK PRO BATTERY LIFE.",
    "Ayo who tf gave you the pass to say 'nigga'? You look like you still ask your mom to cut the crust off your sandwiches.",
    "Nigga? Nigga? You whiter than the inside of an Oreo. Stay in your lane, Walmart brand.",
    "Oh you think you can say 'nigga' cuz you watched 'ATL' one time? You probably from Idaho talking like that.",
    "You calling me 'nigga' but you get nervous when the ice cream truck plays music. Scared ass.",
    "Who let you in the cookout? You saying 'nigga' like you know how to make mac and cheese from scratch.",
    "You claim you my 'nigga' but your biggest struggle is choosing which Netflix show to binge. Privileged ass.",
    "Nigga please, you can't even dance at a wedding without looking like a malfunctioning robot. Rhythmless wonder.",
    "You out here saying 'nigga' but you still wear cargo shorts and New Balance. You're 35 going on 65.",
    "I know you didn't just call me your 'nigga'. You look like you still believe in Santa Claus.",
    "You think you can say 'nigga' cuz you got a black friend? That friend is probably just being polite.",
    "Nigga? Boy you whiter than a sheet of paper in a snowstorm. Your ancestors invented mayonnaise.",
    "You saying 'nigga' like you ever been in a fight. Your only fight is with seasonal allergies.",
    "Who gave you permission? The only 'nigga' you should be saying is 'nigga please sit down'.",
    "You calling people 'nigga' but you can't even handle mild salsa. Your palate is weak, just like your game.",
    "Nigga you ain't from the hood, you from the suburbs with an HOA. You probably call the cops on loud barbecues.",
    "You think you can say 'nigga' cuz you listen to Drake? You probably sing along to 'Hotline Bling' in the shower.",
    "Nigga please, you still sleep with a stuffed animal. You ain't hard, you're barely awake.",
    "You out here saying 'nigga' but you get winded walking up stairs. Out of shape and out of line.",
    "Who let you cook? You saying 'nigga' like you know what a food stamp looks like. Privilege is showing.",
    "Nigga? You look like you still use a flip phone. You're outdated in every way possible.",
    "You calling me 'nigga' but you can't even name three Tupac songs. Fake ass fan.",
    "Nigga you ain't street, you suburban with extra steps. Your idea of danger is a pothole.",
    "You think you can say 'nigga' cuz you played Grand Theft Auto? You probably can't even parallel park.",
    "Nigga please, you still get an allowance from your parents. Get your own money first.",
    "You out here saying 'nigga' but you're scared of thunderstorms. Jump at your own shadow type beat.",
    "Who gave you the green light? You saying 'nigga' like you ever missed a meal. Your biggest hunger is for attention.",
    "Nigga? You look like you drink milk with every meal. Basic and boring.",
    "You calling people 'nigga' but you can't even throw a football spiral. Uncoordinated ass.",
    "Nigga you ain't tough, you tender. You probably cry during Hallmark commercials.",
    "You think you can say 'nigga' cuz you been to a rap concert? You were probably in the nosebleeds.",
    "Nigga please, you still use training wheels on your bike. Literal child behavior.",
    "You out here saying 'nigga' but you're afraid of dogs. Scared of a golden retriever type energy.",
    "Who let you in the function? You saying 'nigga' like you know how to two-step. Rhythm deficit real.",
    "Nigga? You look like you still believe in cooties. Immature as hell.",
    "You calling me 'nigga' but you can't even cook instant ramen right. Useless in the kitchen and in life.",
    "Nigga you ain't cool, you're a tool. You probably still wear braces as an adult.",
    "You think you can say 'nigga' cuz you got a fade? Your barber is probably white too.",
    "Nigga please, you still sleep with a nightlight. Afraid of the dark and afraid of reality.",
    "You out here saying 'nigga' but you get carsick on short drives. Weak stomach, weak character.",
    "Who gave you the pass? You saying 'nigga' like you ever worked a day in your life. Trust fund baby.",
    "Nigga? You look like you still play with Legos. Grow up before you try to grow a pair.",
    "You calling people 'nigga' but you can't even swim. Sink or swim and you sinking.",
    "Nigga you ain't him, you're them. You probably still live in your childhood bedroom.",
    "You think you can say 'nigga' cuz you got a tattoo? It's probably a tribal design from 2005.",
    "Nigga please, you still ask for help tying your shoes. Incompetent at life.",
    "You out here saying 'nigga' but you're allergic to grass. Can't even touch grass properly.",
    "Who let you in the studio? You saying 'nigga' like you can freestyle. Your best rhyme is cat/hat.",
    "Nigga? You look like you still use AOL email. Stuck in the past like your mindset.",
    "You calling me 'nigga' but you can't even drive stick. Manual failure, just like your social skills.",
    "Nigga you ain't about that life, you about that wifi life. Your biggest risk is a weak password.",
    "You think you can say 'nigga' cuz you wear Jordans? You probably keep the tags on them.",
    "Nigga please, you still believe in the tooth fairy. Delusional and desperate.",
    "You out here saying 'nigga' but you can't handle spicy food. Your tongue is as weak as your game.",
    "Who gave you permission? You saying 'nigga' like you ever been outside past 9 PM. Curfew king.",
    "Nigga? You look like you still use dial-up internet. Slow in every aspect of life.",
    "You calling people 'nigga' but you can't even change a tire. Useless when it matters most.",
    "Nigga you ain't real, you're a deal. You probably still shop at the kids' section.",
    "You think you can say 'nigga' cuz you been to a cookout? You probably brought store-bought potato salad.",
    "Nigga please, you still watch cartoons on Saturday morning. You're not a kid, you're just childish.",
    "You out here saying 'nigga' but you're scared of elevators. Claustrophobic and cowardly.",
    "Who let you in the cypher? You saying 'nigga' like you can beatbox. You sound like a broken dishwasher.",
    "Nigga? You look like you still use a paper map. Can't navigate life or conversations.",
    "You calling me 'nigga' but you can't even grill a burger. Burn everything you touch.",
    "Nigga you ain't street smart, you street dumb. You probably get lost in your own neighborhood.",
    "You think you can say 'nigga' cuz you got a chain? It's probably from Claire's.",
    "Nigga please, you still believe in horoscopes. Your sign is 'delusional'.",
    "You out here saying 'nigga' but you can't parallel park. Can't maneuver life either.",
    "Who gave you the mic? You saying 'nigga' like you can sing. You sound like a dying cat.",
    "Nigga? You look like you still use a VCR. Outdated technology, outdated mindset.",
    "You calling people 'nigga' but you can't even do a push-up. Physically and mentally weak.",
    "Nigga you ain't about action, you're about distraction. Your biggest move is changing your profile picture.",
    "You think you can say 'nigga' cuz you got a durag? You probably sleep in it like pajamas.",
    "Nigga please, you still play Pokémon Go. Your biggest catch is disappointment.",
    "You out here saying 'nigga' but you're scared of bees. Buzz off, literally.",
    "Who let you in the studio? You saying 'nigga' like you can produce. Your beats are weaker than your game.",
    "Nigga? You look like you still use Myspace. Socially irrelevant.",
    "You calling me 'nigga' but you can't even swim. You sink in shallow water and deep conversations.",
    "Nigga you ain't making moves, you're making mistakes. Your biggest accomplishment is breathing.",
    "You think you can say 'nigga' cuz you got a snapback? You wear it backwards and it shows.",
    "Nigga please, you still collect beanie babies. Your investments are as bad as your judgment.",
    "You out here saying 'nigga' but you can't handle caffeine. Jittery and jumpy like your personality.",
    "Who gave you the floor? You saying 'nigga' like you can dance. You move like a baby deer on ice.",
    "Nigga? You look like you still use Windows 95. Your operating system needs an update.",
    "You calling people 'nigga' but you can't even cook an egg. Can't handle heat in the kitchen or the streets.",
    "Nigga you ain't building, you're breaking. Your only construction is deconstructing your own credibility.",
    "You think you can say 'nigga' cuz you got a tattoo sleeve? It's probably all tribal and Chinese symbols.",
    "Nigga please, you still believe in Bigfoot. Your reality is as fictional as your street cred.",
    "You out here saying 'nigga' but you're scared of commitment. Can't commit to a relationship or a hairstyle.",
    "Who let you in the booth? You saying 'nigga' like you can rap. Your flow is weaker than your handshake.",
    "Nigga? You look like you still use a pager. Can't get with the times or the rhymes.",
    "You calling me 'nigga' but you can't even fix a leaky faucet. Useless with tools and common sense.",
    "Nigga you ain't making waves, you're making puddles. Your impact is as small as your ambition.",
    "You think you can say 'nigga' cuz you got a gold tooth? It's probably just gold-plated.",
    "Nigga please, you still play with action figures. Your idea of action is moving them around.",
    "You out here saying 'nigga' but you're scared of thunderstorms. Jump at loud noises type energy.",
    "Who gave you the stage? You saying 'nigga' like you can perform. Your act is tired, just like your jokes.",
    "Nigga? You look like you still use cassette tapes. Your taste in music and life is outdated.",
    "You calling people 'nigga' but you can't even grow a beard. Patchy in facial hair and personality.",
    "Nigga you ain't dropping gems, you're dropping dimes. And by dimes, I mean worthless opinions.",
    "You think you can say 'nigga' cuz you got a pitbull? You probably got it from a breeder, not the streets.",
    "Nigga please, you still believe in fairy tales. Your life is a fantasy, just like your credibility.",
    "You out here saying 'nigga' but you can't handle rejection. Your ego is as fragile as your confidence.",
    "Who let you in the circle? You saying 'nigga' like you belong. You're as welcome as a fart in an elevator.",
    "I KNOW YOU'RE TYPING THIS FROM YOUR DORM ROOM AT A PRIVATE COLLEGE. LOG OFF.",
]   