SLANG_MAP = {
    "hi": "yo wassup", "hello": "yo", "how are you": "how u livin", "friend": "cuz",
    "man": "nigga", "police": "the 12", "gun": "strap", "money": "bread", "good": "fire",
    "bad": "wack", "brother": "homie", "sister": "shawty", "girl": "bitch", "house": "crib",
    "cool": "dope", "really": "no cap", "truth": "on god", "scared": "pussy", "ok": "bet",
    "yes": "yuh", "no": "nah", "please": "on my mama", "thank you": "respect",
    "bye": "peace out", "whats going on": "what it do", "what are you doing": "what you on",
    "where are you": "where you at", "leave": "dip", "run away": "skedaddle",
    "tired": "beat", "angry": "heated", "calm down": "chill", "relax": "kick back",
    "fight": "throw hands", "win": "catch a W", "lose": "take an L", "joke": "clown",
    "lying": "cappin", "stop lying": "cut the cap", "trust me": "believe that",
    "look": "peep", "listen": "hear me out", "understand": "feel me", "agree": "facts",
    "disagree": "miss me with that", "embarrassing": "cringe", "impressive": "tough",
    "amazing": "go crazy", "popular": "lit", "party": "function", "drunk": "faded",
    "high": "smacked", "dangerous": "sketchy", "suspicious": "shady", "steal": "jack",
    "argument": "back-and-forth", "problem": "issue", "plan": "move", "style": "drip",
    "clothes": "fit", "shoes": "kicks", "car": "whip", "fast": "movin different",
    "slow": "draggin", "quiet": "lowkey", "obvious": "highkey", "serious": "deadass",
    "nothing": "ain't shit", "everything": "the whole thing", "right now": "right quick",
    "later": "in a minute", "left": "dipped", "leaving": "dipping", "run": "dash",
    "ran": "dashed", "running": "dashin", "escape": "slide", "escaped": "slid",
    "escaping": "slidin", "relaxed": "chilled", "relaxing": "chillin", "hang out": "kick it",
    "hung out": "kicked it", "hanging out": "kickin it", "fought": "threw hands",
    "fighting": "throwin hands", "argued": "went back and forth", "arguing": "goin back and forth",
    "lied": "capped", "flex": "flex", "flexed": "flexed", "flexin": "flexin",
    "stunt": "stunt", "stunted": "stunted", "stuntin": "stuntin",
    "tk": "that one dude", "shikyo": "the plug", "discord": "the block",
    "i'm": "I be", "you're": "u is", "they're": "they is", "we're": "we is",
    "going to": "gon'", "want to": "wanna", "trying to": "tryna",
    "because": "cuz", "about": "'bout", "and": "n'", "with": "wit'",
    "bounty": "hit", "contract": "paperwork", "assassin": "ghost", "target": "mark",
    "rich": "ballin", "poor": "broke", "expensive": "taxin", "cheap": "budget",
    "food": "eats", "drink": "sippin", "sleep": "crash", "wake up": "rise n shine",
    "work": "grind", "job": "gig", "boss": "OG", "employee": "worker bee",
    "smart": "brainy", "dumb": "slow", "funny": "hilarious", "boring": "dry",
    "hot": "fire", "cold": "ice cold", "big": "massive", "small": "lil",
    "new": "fresh", "old": "vintage", "clean": "spotless", "dirty": "nasty",
}